highlighter: pygments
permalink: pretty
markdown: kramdown

title: Neovim
description: "vim's rebirth for the 21st century"

news:
    name: Neovim Newsletter
    authors: Neovim Community
    url: https://neovim.org/news
    feed: /news.xml

url: https://neovim.org

gems:
    - jekyll-redirect-from
    - jekyll-mentions

exclude:
    - CNAME
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - vendor/
